### ISSUE TITLE
Save to file

### ISSUE THREAD

**Issue by iamtekeste** [hokein/electron-sample-apps#26]
Awesome demo!
I was wondering if there was a way to save the recording into a file?
Thanks!

**Comment by iamtekeste** [comment]
Save the file as save it as `recording.mp4` or `recording.webm`. Instead of displaying it on a `video `tag.

**Comment by styfle** [comment]
@hokein In the `desktop-capture` project, it gives you a button to Enable Capture but the stream is sent to the `<video>` tag. How do you save the stream to a file?

**Comment by iamtekeste** [comment]
@hokein Sorry I forgot to mention the sample folder name. Thank you @styfle for clarifying that one :+1:

**Comment by hokein** [comment]
I'd suggest you to seek help in electron [community](https://github.com/electron/electron#community).
