### ISSUE TITLE
Flash example does not work on Linux

### ISSUE THREAD

**Issue by TomBZombie** [hokein/electron-sample-apps#32]
I'm not sure whether I need a specific libpepflash.so version which is the problem but I'm using the one provided by the arch pepperflash package  and just get "Couldn't load pluigin". I'm using the sample main.js and current.

I get no errors or messages in stdout/stderr only "Couldn't load plugin" where the flash element should be. Do I need a specific version of the .so file or should any work? I've tried  different commands for the version string, the one from your example and the one reported by Chromium using the same .so file, I still can't get it to load. How do I go about debugging this?

**Comment by hokein** [comment]
Yes, the version of Pepper Flash Plugin should be aligned with the one being used in the Electron's Chromium version.
