### ISSUE TITLE
How to import the client certificat into electron app

### ISSUE THREAD

**Issue by jwl2006** [hokein/electron-sample-apps#39]
Hi,

I am wondering how to import rootCA.crt and client.p12 to the electron client? Thanks

**Comment by hokein** [comment]
There should be an electron API for it. I think you could find more details in the discussion of https://github.com/electron/electron/issues/1956.

The `readme` of `client-certificate` sample might not keep with the latest status of electron, pull requests are always welcome 😄 

I'm closing it as this is not an issue related to this repository.
