### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jdittrich** [hokein/electron-sample-apps#4]
**Story:** As a Programmer, I would like to know if I can incorporate code from this repo in my own projects. 

**Current State:** there is no license information

**Suggested Fix**: Add a License (MIT, Apache, GPL or just "standard copyright"…), if this is possible 

(seemingly, the original [Example Chrome Apps](https://github.com/GoogleChrome/chrome-app-samples) Repo has an [Apache license](https://github.com/GoogleChrome/chrome-app-samples/blob/master/LICENSE), while the [nw.js examples](https://github.com/zcbenz/nw-sample-apps) does not have a LICENSE stated.)

**Comment by hokein** [comment]
It's something I plan to do.

Most of the apps are copied and modified from https://github.com/GoogleChrome/chrome-app-samples, but some of it are from https://developer.chrome.com/extensions/samples, which has no licence. I will add a license in each example app directory.
