### ISSUE TITLE
Set closable notification

### ISSUE THREAD

**Issue by suku-h** [hokein/electron-sample-apps#41]
My app syncs with another software in the background. If the other software is not open then the data will not be sent to my app. Hence, I would like to add a closable notification. HOw can I do this?

**Comment by hokein** [comment]
Issues of `electron-sample-apps` are for feature requests and bug reports. I'd suggest you asking questions about using Electron [community](https://github.com/electron/electron#community) or the [Slack Channel](http://atom-slack.herokuapp.com/).
