### ISSUE TITLE
webgl example does not work in webview of electron

### ISSUE THREAD

**Issue by zwyxsyu** [hokein/electron-sample-apps#44]
When i run the WebGL example, it shows "Your graphics card does not seem to support WebGL, Find out how to get it here". But i can get the WebGL object in the browser normally.

What is the possible reason?

![webgl](https://user-images.githubusercontent.com/15085627/29807640-6b7224a2-8cc7-11e7-9f6a-4cebf0639eae.png)

**Comment by cg-cnu** [comment]
Adding `app.commandLine.appendSwitch('--ignore-gpu-blacklist');` in your `main.js` should fix the issue.
Thanks! 😄

**Comment by hokein** [comment]
visit "chrome://gpu" probably gives you some clues.
