### ISSUE TITLE
Improve menu application

### ISSUE THREAD

**Issue by cg-cnu** [hokein/electron-sample-apps#46]
Last time I cloned, which is a while back; menus app has some [ commented code ](https://github.com/hokein/electron-sample-apps/commit/32717cee9186d6f3c39f44fedd976da80b9f9ac6#diff-260501c94f05fae320c29cd9bc107340) Which looked like something cool to implement. I tried fixing it but hit few snags :slightly_frowning_face:  I am doing a pr now to see if any one can help me out :smile:

**Comment by cg-cnu** [comment]
I recorded a video to give more info about the issue... [video](https://youtu.be/G8Be1rCXhHQ) Selecting the menu item is invoking the main menu.

**Comment by cg-cnu** [comment]
@hokein I feel like this is a bug in electron. I posted in the electron discourse forum but didn't got any reply. Did you got the chance to look into it ? Do you think I should create an issue in electron github? :slightly_smiling_face:

**Comment by hokein** [comment]
@cg-cnu, sorry, currently I don't have bandwidth to look into it. But if you think it is an electron bug, just create an issue in electron's github repo (with a minimal reproducible application).

**Comment by cg-cnu** [comment]
@hokein. That's completely fine. I will create an issue and track it. Thanks :smile:

**Comment by hokein** [comment]
I'm closing it out, free free to reopen it.

**Comment by cg-cnu** [comment]
@hokein Sorry didn't got the chance to work on it again. I will look into it later. Sorry for the trouble.

**Comment by hokein** [comment]
@cg-cnu no problem. Contributions are always welcome :)
