### ISSUE TITLE
Service Worker example fails on Windows

### ISSUE THREAD

**Issue by joncombe** [hokein/electron-sample-apps#48]
Thank you for this project, it is very helpful.

I have a problem on Windows 10. When I run the service-worker/mock-response example, the code doesn't run as expected and I see errors in the console:

`Error DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/plain').`

If I paste the navigator.serviceWorker.register code directly into the console, it gives slightly more feedback:

`The script has an unsupported MIME type ('text/plain')
Failed to load resource: net::ERR_INSECURE_RESPONSE`

The same code runs perfectly on my macOS Sierra machine. Thank you in advance.

**Comment by hokein** [comment]
I haven't tried it on Windows 10, it seems a bug of electron,  I'd suggest you filing/redirecting the bug there.

**Comment by joncombe** [comment]
Thank you very much for your comment and sorry for my slow reply. I will do as you suggest.

**Comment by joncombe** [comment]
For those who may find this thread in future, the solution can be found here: https://github.com/electron/electron/issues/10642

**Comment by joseluiscampos** [comment]
In my case, in windows registry, in HKEY_CLASSES_ROOT there is a subfolder named .js and in the Content Type key I changed from text/plain to application/javascript. 

Thanks @joncombe
