### ISSUE TITLE
unable to get desktop-capture to save system audio

### ISSUE THREAD

**Issue by asmallfurrywombat** [hokein/electron-sample-apps#56]
so far no luck trying to get the desktop-capture sample to save system audio. I'm using electron 1.7.9 on ubuntu 17.10 and audio is output to the speakers from a browser page. I've tried the solution recommended at https://github.com/electron/electron/issues/8589 but no luck. I've also tried setting:
    audio: {
        mandatory: {
            chromeMediaSource: "desktop"
        }
    }
as per https://electronjs.org/docs/api/desktop-capturer but again no luck. If i hit 'enable' with either of these methods, the capture area remains blank. If audio is set to false, the capture works. 

How can i save system audio while capturing frames for a specific window?

**Comment by hokein** [comment]
@asmallfurrywombat Can you report this issue to electron repository? This repository isn't intended for the electron-specific issues.
