### ISSUE TITLE
Why have you used the non-standard zepto.min.js instead of the standard jQuery that everybody uses?

### ISSUE THREAD

**Issue by prahladyeri** [hokein/electron-sample-apps#58]
I'm quite new to electron framework and this is more of a query than an issue. I just wanted to know the reason for using `zepto` library which is anyway compatible with jquery in your sample code for `mini-code-editor`. If I use jquery instead, is there going to be an issue while using the app?

**Comment by limeb** [comment]
@prahladyeri zepto is smaller not necessarily faster and shorter code.  That is basically the only reason to use it IMO.
