### ISSUE TITLE
npm err!: Missing script start.

### ISSUE THREAD

**Issue by nmcain** [hokein/electron-sample-apps#59]
The app no longer starts

**Comment by Leonardonline** [comment]
Maybe you tried to run a `npm start` command instead of `electron <electron-sample-apps-path>/<sample-name>`. 
Below the instructions  (contained in the Readme!)

> ## How to run apps
> 
> 1. Install Electron via `npm install -g electron`.
> 
> 2. Run the sample via `electron <electron-sample-apps-path>/<sample-name>`.

**Comment by hokein** [comment]
@Leonardonline mentioned above, `npm start` is not supported yet.
