### ISSUE TITLE
Not compatible with the latest version of Electron

### ISSUE THREAD

**Issue by MakarenkoPavel** [hokein/electron-sample-apps#63]
Not compatible with latest version of Electron. 
The samples start works only after adding few lines to package json file:
"scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^4.1.4"
  }

**Comment by mdabdul330** [comment]
require is not working in html in latest version. Can we not share objects in ELectron ?

**Comment by wangzhijun97** [comment]
> require is not working in html in latest version. Can we not share objects in ELectron ?

I got the same problem！it confusing me，but I hava nothing to do with it.

**Comment by dersteps** [comment]
Same here. `require` does not seem to work. All samples start, but buttons etc. doesn't do anything. Would be grateful if this was fixed, as I am trying to learn with the examples
