### ISSUE TITLE
file-explorer demo not working on windows

### ISSUE THREAD

**Issue by drpain** [hokein/electron-sample-apps#73]
Sadly the file-explorer demo doesn't work on windows, however the mini code editor does. 

![image](https://user-images.githubusercontent.com/1902518/87831255-4b6e1d00-c883-11ea-820c-b14fb3bf614a.png)

**Comment by saxobroko** [comment]
Also experiencing this

**Comment by millerdrew** [comment]
Experiencing this on mac as well

**Comment by successful-fella** [comment]
Same. This shows up in console.

`Cannot destructure property 'Menu' of 'remote' as it is undefined.`

**Comment by hokein** [comment]
should be fixed in #75
